### ISSUE TITLE
Tensorr

### ISSUE THREAD

**Issue by tdrvlad** [sayakpaul/portfolio#10]
Hi, I run the TensorRT conversion script just as in your demo. I get some curious bugs (attached image). The thing is, I successfully converted a model at my first time. Some time later, when I tried to run the **same** script again, these errors popped up. Any help would be greatly appreciated, thank you!

<img width="474" alt="TensorRT bug" src="https://user-images.githubusercontent.com/45488144/122992902-555fa080-d3af-11eb-821c-7653ece907a5.PNG">

**Comment by sayakpaul** [comment]
Could be because of TensorFlow's update to 2.5. Would suggest opening an issue in the TensorFlow repository.

**Comment by tdrvlad** [comment]
Thank you very much for the response.

**Comment by tdrvlad** [comment]
And congratulations for the article. Very informative and on-point! It
helped me a lot :)
